### ISSUE TITLE
Support SADDEX command

### ISSUE THREAD

**Issue by zidokobik** [cunla/fake-dragonflydb#21]
It seems like the [SADDEX](https://www.dragonflydb.io/docs/command-reference/sets/saddex) command, which is Dragonfly-specific, is not supported. It's the main reason I use dragonflydb over instead of redis.
Any plan to implement it ?

**Comment by cunla** [comment]
Hi, thanks for reporting this.
Yes, it can be easily implemented.

**Comment by cunla** [comment]
Do you mind opening an issue for this in fakeredis. I am going to implement dragonfly support in fakeredis.

By the way, how are you calling the `SADDEX` command considering it is not in the redis-py client? do you use direct commands?

**Comment by cunla** [comment]
https://github.com/cunla/fakeredis-py/releases/tag/v2.26.0
